### ISSUE TITLE
The node does not fetch the model

### ISSUE THREAD

**Issue by sandra-calvo** [ibm-early-programs/node-red-contrib-watson-machine-learning#18] opened 2019-09-04 11:28 UTC
Probably because of the authentication method, but the current version does not work. 
The way it used to authenticate the service has been deprecated. It needs an update.

**Comment by chughts** [comment] 2019-09-04 16:01
I think this is a duplicate of #17 . I am happy to accept pull requests with a fix.

**Closed as completed by chughts** 2019-09-04 16:01 UTC
